blank_issues_enabled: false
contact_links:
  - name: Conda Build Issues/Features
    url: https://github.com/conda/conda-build/issues
    about: Anything related to the "conda-build" project should go here
  - name: Package Request
    url: https://github.com/ContinuumIO/anaconda-issues/
    about: A specific Conda package from Anaconda ('defaults' channel)
