name: Canary builds

on:
  workflow_run:
    workflows:
      - CI tests
    branches:
      - master
    types:
      - completed

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            subdir: linux-64
          - runner: macos-latest
            subdir: osx-64
          - runner: windows-latest
            subdir: win-64
    runs-on: ${{ matrix.runner }}
    steps:
      # Clean checkout of specific git ref needed for package metadata version
      # which needs env vars GIT_DESCRIBE_TAG and GIT_BUILD_STR:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0

      - name: Create and upload canary build
        uses: conda/actions/canary-release@v22.1.3
        with:
          package-name: conda
          subdir: ${{ matrix.subdir }}
          anaconda-org-channel: conda-canary
          anaconda-org-label: dev
          anaconda-org-token: ${{ secrets.ANACONDA_ORG_TOKEN }}
