name: CI images

on:
  schedule:
    - cron:  '0 0 * * 0'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/ci-images.yml'
      - 'tests/requirements.txt'
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/ci-images.yml'
      - 'tests/requirements.txt'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-ci

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            suffix=-linux-python${{ matrix.python }}

      - name: Build & push Python ${{ matrix.python }}
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          build-args: python_version=${{ matrix.python }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.ref == 'refs/heads/master' }}
